In [1]:
from sklearn.pipeline import Pipeline
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
import sys
import os

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(PROJECT_ROOT)

In [3]:
from pipelines.feature_contract import (
    FEATURE_COLUMNS,
    TARGET_COLUMN
)

In [4]:
# Load dataset
df = pd.read_csv("../data/features/failure_training_dataset.csv")

In [5]:
# Separate classes
df_pos = df[df["failure"] == 1]
df_neg = df[df["failure"] == 0]

# Keep all failures
# Downsample negatives (example: 10x failures)
neg_sample = df_neg.sample(
    n=len(df_pos) * 10,
    random_state=42
)

df_balanced = pd.concat([df_pos, neg_sample]).sample(frac=1)

print(df_balanced["failure"].value_counts(normalize=True))

failure
0.0    0.909091
1.0    0.090909
Name: proportion, dtype: float64

In [6]:
df_balanced.shape

(1166, 17)

In [7]:
df_balanced.head()

,pressure_gas_lift,pressure_production_casing,valvestatus_dhsv,valvestatus_master1,valvestatus_master2,valvestatus_xmastree,valvestatus_shutdowngaslift,pressure_toptubing,flow_gaslift,temp_checkproduction,temp_downholegauge,temp_toptubing,failure,failure_rate_per_year_expected,availability_pct,mtbf_days,mttr_days
2119252,40.072919,35.698563,1.0,0.990782,0.995557,0.000433,0.999172,1.766832e+07,0.001749,25.323238,70.934908,56.071070,0.0,0.3394,99.609,1075.429,7.129
1062175,40.072919,35.698563,1.0,0.990782,0.995557,0.000433,0.999172,1.709853e+07,0.005547,26.086119,70.934908,79.231127,0.0,0.6018,100.000,606.503,1.110
1882341,40.072919,35.698563,1.0,0.990782,0.995557,0.000433,0.999172,9.214598e+06,3.231870,78.253995,70.934908,93.340387,0.0,0.0876,100.000,4166.667,19.772
2007923,40.072919,35.698563,1.0,0.990782,0.995557,0.000433,0.999172,8.319669e+06,4.713423,74.933942,70.934908,90.739898,0.0,0.2714,96.624,1344.959,12.324
1775663,40.072919,35.698563,1.0,0.990782,0.995557,0.000433,0.999172,4.839553e+06,3.643997,59.056596,70.934908,84.777990,0.0,0.8021,99.930,455.074,0.257

In [8]:
# Safety check
assert TARGET_COLUMN in df.columns, "Target column missing!"
for col in FEATURE_COLUMNS:
    assert col in df.columns, f"Missing feature: {col}"

In [9]:
print("✅ Dataset loaded and validated")
print("Shape:", df.shape)

✅ Dataset loaded and validated
Shape: (2600000, 17)

In [10]:
X = df_balanced[FEATURE_COLUMNS]
y = df_balanced[TARGET_COLUMN]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train failure rate:", y_train.mean())
print("Test failure rate:", y_test.mean())

Train failure rate: 0.09120171673819742
Test failure rate: 0.08974358974358974

In [11]:
X

,pressure_gas_lift,pressure_production_casing,pressure_toptubing,flow_gaslift,temp_toptubing,temp_downholegauge,temp_checkproduction,valvestatus_dhsv,valvestatus_master1,valvestatus_master2,valvestatus_xmastree,valvestatus_shutdowngaslift,mtbf_days,mttr_days,failure_rate_per_year_expected,availability_pct
2119252,40.072919,35.698563,1.766832e+07,0.001749,56.071070,70.934908,25.323238,1.0,0.990782,0.995557,0.000433,0.999172,1075.429,7.129,0.3394,99.609
1062175,40.072919,35.698563,1.709853e+07,0.005547,79.231127,70.934908,26.086119,1.0,0.990782,0.995557,0.000433,0.999172,606.503,1.110,0.6018,100.000
1882341,40.072919,35.698563,9.214598e+06,3.231870,93.340387,70.934908,78.253995,1.0,0.990782,0.995557,0.000433,0.999172,4166.667,19.772,0.0876,100.000
2007923,40.072919,35.698563,8.319669e+06,4.713423,90.739898,70.934908,74.933942,1.0,0.990782,0.995557,0.000433,0.999172,1344.959,12.324,0.2714,96.624
1775663,40.072919,35.698563,4.839553e+06,3.643997,84.777990,70.934908,59.056596,1.0,0.990782,0.995557,0.000433,0.999172,455.074,0.257,0.8021,99.930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527160,40.072919,35.698563,1.884301e+07,0.003302,65.184462,70.934908,25.193087,1.0,0.990782,0.995557,0.000433,0.999172,311.678,1.614,1.1711,99.116
1321000,40.072919,35.698563,9.024772e+06,5.907095,88.597927,70.934908,73.059164,1.0,0.990782,0.995557,0.000433,0.999172,893.897,10.000,0.4083,98.904
16403,40.072919,35.698563,1.421993e+07,0.015560,96.856897,70.934908,59.187281,1.0,0.990782,0.995557,0.000433,0.999172,1250.000,0.868,0.2920,99.952
1240823,40.072919,35.698563,1.548706e+07,0.034692,93.772971,70.934908,25.349098,1.0,0.990782,0.995557,0.000433,0.999172,707.543,0.245,0.5159,99.933
2563478,40.072919,35.698563,1.578042e+07,0.002168,85.001509,70.934908,27.055786,1.0,0.990782,0.995557,0.000433,0.999172,511.880,0.434,0.7131,100.000

In [12]:
X_train

,pressure_gas_lift,pressure_production_casing,pressure_toptubing,flow_gaslift,temp_toptubing,temp_downholegauge,temp_checkproduction,valvestatus_dhsv,valvestatus_master1,valvestatus_master2,valvestatus_xmastree,valvestatus_shutdowngaslift,mtbf_days,mttr_days,failure_rate_per_year_expected,availability_pct
665603,40.072919,35.698563,7.651159e+06,2.624434,91.613696,70.934908,73.996244,1.0,0.990782,0.995557,0.000433,0.999172,797.281,1.000,0.4578,100.000
437045,40.072919,35.698563,9.480856e+06,2.435934,93.899207,70.934908,78.886306,1.0,0.990782,0.995557,0.000433,0.999172,322.597,0.809,1.1314,99.778
2542599,40.072919,35.698563,8.662557e+06,-0.003017,94.250030,70.934908,78.389240,1.0,0.990782,0.995557,0.000433,0.999172,1031.533,4.021,0.3538,100.000
18829,40.072919,35.698563,1.618770e+07,0.010195,93.679596,70.934908,31.550795,1.0,0.990782,0.995557,0.000433,0.999172,601.880,0.937,0.6064,99.795
2155065,40.072919,35.698563,7.433447e+06,2.511232,92.336077,70.934908,72.861192,1.0,0.990782,0.995557,0.000433,0.999172,912.654,7.098,0.3999,99.222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243580,40.072919,35.698563,1.502438e+07,0.019152,91.760507,70.934908,25.512701,1.0,0.990782,0.995557,0.000433,0.999172,1216.558,0.243,0.3000,99.978
1406849,40.072919,35.698563,1.634741e+07,0.066579,95.776303,70.934908,31.613198,1.0,0.990782,0.995557,0.000433,0.999172,535.258,0.305,0.6819,99.950
1967372,40.072919,35.698563,9.411981e+06,1.589218,95.414997,70.934908,78.336508,1.0,0.990782,0.995557,0.000433,0.999172,1723.020,30.000,0.2118,91.781
16475,40.072919,35.698563,1.515948e+07,0.015369,96.890777,70.934908,27.169223,1.0,0.990782,0.995557,0.000433,0.999172,1666.667,3.156,0.2190,100.000
1616402,40.072919,35.698563,1.694606e+07,0.003184,66.697798,70.934908,25.307460,1.0,0.990782,0.995557,0.000433,0.999172,130.737,5.000,2.7919,96.804

In [13]:
X = df[FEATURE_COLUMNS]

print("NaN counts per feature:")
print(X.isna().sum()[X.isna().sum() > 0])

NaN counts per feature:
Series([], dtype: int64)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, average_precision_score

model_lr = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    n_jobs=-1
)

model_lr.fit(X_train, y_train)

y_pred = model_lr.predict(X_test)
y_prob = model_lr.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("PR-AUC:", average_precision_score(y_test, y_prob))

              precision    recall  f1-score   support

         0.0       0.94      0.65      0.77       213
         1.0       0.14      0.57      0.22        21

    accuracy                           0.65       234
   macro avg       0.54      0.61      0.50       234
weighted avg       0.87      0.65      0.72       234

PR-AUC: 0.17805876934815087

e:\Research_Paper\oil_gas_ai\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

In [15]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_leaf=50,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)

In [16]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("PR-AUC:", average_precision_score(y_test, y_prob))

              precision    recall  f1-score   support

         0.0       0.96      0.74      0.83       213
         1.0       0.20      0.67      0.31        21

    accuracy                           0.73       234
   macro avg       0.58      0.70      0.57       234
weighted avg       0.89      0.73      0.79       234

PR-AUC: 0.296937988494263

In [17]:
import numpy as np

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

scale_pos_weight = neg / pos
print("scale_pos_weight:", scale_pos_weight)

scale_pos_weight: 9.964705882352941

In [18]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="aucpr",
    tree_method="hist",
    random_state=42,
    scale_pos_weight=scale_pos_weight,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [200, 400],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.7, 0.85],
    "colsample_bytree": [0.7, 0.85],
    "min_child_weight": [5, 10, 20],
    "gamma": [0, 1, 5]
}

grid = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring="average_precision",  # PR-AUC
    cv=3,
    verbose=2,
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("✅ Best PR-AUC:", grid.best_score_)
print("✅ Best Parameters:")
print(grid.best_params_)

Fitting 3 folds for each of 648 candidates, totalling 1944 fits
✅ Best PR-AUC: 0.36904303147378786
✅ Best Parameters:
{'colsample_bytree': 0.85, 'gamma': 5, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 200, 'subsample': 0.85}

In [19]:
best_xgb = grid.best_estimator_

best_xgb.fit(X_train, y_train)

y_prob = best_xgb.predict_proba(X_test)[:, 1]

In [20]:
import numpy as np
from sklearn.metrics import precision_recall_curve, classification_report

precision, recall, thresholds = precision_recall_curve(y_test, y_prob)

f1 = 2 * precision * recall / (precision + recall + 1e-9)
best_threshold = thresholds[np.argmax(f1)]

print("✅ Best threshold:", best_threshold)

y_pred = (y_prob >= best_threshold).astype(int)

print(classification_report(y_test, y_pred))

✅ Best threshold: 0.7708154
              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97       213
         1.0       0.71      0.57      0.63        21

    accuracy                           0.94       234
   macro avg       0.83      0.77      0.80       234
weighted avg       0.94      0.94      0.94       234

In [31]:
X_tain_pred = grid.predict(X_train)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
D

Accuracy: 0.9401709401709402

In [24]:
import joblib
import os

os.makedirs("models/failure", exist_ok=True)

joblib.dump(model, "models/failure/xgb_failure_model.pkl")

print("✅ Model saved successfully")

✅ Model saved successfully

In [25]:
import json

best_threshold = 0.22046171  # your tuned threshold

with open("models/failure/threshold.json", "w") as f:
    json.dump(
        {"failure_threshold": best_threshold},
        f,
        indent=4
    )

print("✅ Threshold saved")

✅ Threshold saved

In [26]:
from pipelines.feature_contract import FEATURE_COLUMNS, TARGET_COLUMN

feature_contract = {
    "features": FEATURE_COLUMNS,
    "target": TARGET_COLUMN
}

with open("models/failure/feature_contract.json", "w") as f:
    json.dump(feature_contract, f, indent=4)

print("✅ Feature contract saved")

✅ Feature contract saved

In [27]:
metadata = {
    "model_type": "XGBoostClassifier",
    "task": "Equipment Failure Prediction",
    "threshold": best_threshold,
    "metric": "PR-AUC",
    "pr_auc": 0.2627,
    "training_samples": len(X_train),
    "positive_rate": y_train.mean(),
    "date_trained": "2026-01-17",
    "author": "Oil & Gas AI Pipeline"
}

with open("models/failure/metadata.json", "w") as f:
    json.dump(metadata, f, indent=4)

print("✅ Metadata saved")

✅ Metadata saved

In [28]:
import joblib
import json

model = joblib.load("models/failure/xgb_failure_model.pkl")

with open("models/failure/threshold.json") as f:
    threshold = json.load(f)["failure_threshold"]

with open("models/failure/feature_contract.json") as f:
    FEATURE_COLUMNS = json.load(f)["features"]

print("🚀 Model ready for inference")

🚀 Model ready for inference

In [29]:
X_new = df_balanced[FEATURE_COLUMNS]

y_prob = model.predict_proba(X_new)[:, 1]
y_pred = (y_prob >= threshold).astype(int)

In [30]:
import os

print(os.listdir("models/failure"))

['feature_contract.json', 'metadata.json', 'threshold.json', 'xgb_failure_model.pkl']